# Generated by Django 3.1.7 on 2021-04-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('model_name', models.CharField(max_length=120)),
                ('spec', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to='images')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brands')),
            ],
        ),
    ]
