# Generated by Django 3.1.7 on 2021-06-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avlbl_seats',
            field=models.IntegerField(default=0),
        ),
    ]
