# Generated by Django 3.1.7 on 2021-06-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_avlbl_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='team',
            new_name='team_or_performer',
        ),
    ]
