# Generated by Django 3.1.7 on 2021-06-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210605_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('no_of_tickets', models.IntegerField(default=1)),
                ('booking_date', models.DateField(auto_now=True)),
                ('mobile_number', models.IntegerField()),
                ('status', models.CharField(choices=[('booked', 'booked'), ('cancel', 'cancel')], default='booked', max_length=10)),
                ('total', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
