# Generated by Django 3.1.7 on 2021-06-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbook',
            name='mobile_number',
            field=models.CharField(max_length=12),
        ),
    ]
