# Generated by Django 3.1.7 on 2021-05-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='img',
        ),
    ]
