# Generated by Django 3.1.7 on 2021-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbook',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('cancel', 'cancel')], default='booked', max_length=10),
        ),
    ]
