# Generated by Django 3.1.7 on 2021-05-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
    ]
