# Generated by Django 3.1.7 on 2021-05-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
