# Generated by Django 3.1.7 on 2021-05-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreation',
            name='account_type',
            field=models.CharField(default='savings', max_length=50),
        ),
    ]
